import React from "react";
import "./Rarity.css";
import SectionTitle from "../../components/SectionTitle/SectionTitle";
import alert from "../../assets/images/alert.png";

const rarity_types = [
  "10,000 Bakso Maniacs",
  "Common - No Accessories",
  "Less Common - Accessorized",
  "Rare - Crown",
  "Super Rare - Steam ",
];

const rarity_traits = [
  {
    num: 60,
    text: "Head Tops",
  },
  {
    num: 16,
    text: "Mouths",
  },
  {
    num: 15,
    text: "Glasses",
  },
  {
    num: 12,
    text: "Eyes",
  },
  {
    num: 10,
    text: "Backgrounds",
  },
  {
    num: 10,
    text: "Bodies",
  },
  {
    num: 10,
    text: "Cheeks",
  },
  {
    num: 10,
    text: "Ties",
  },
  {
    num: 9,
    text: "Eye Brows",
  },
  {
    num: 8,
    text: "Clothing",
  },
  {
    num: 6,
    text: "Tattoos",
  },
  {
    num: 1,
    text: "Rare Steam",
  },
];

const Rarity = () => {
  return (
    <section className="rarity" id="rarity">
      <div className="container">
        <div className="row">
          <div
            className="d-flex flex-column align-items-center col-lg-8 mx-auto"
            data-aos="fade-down"
            data-aos-duration="700"
            data-aos-delay="1000"
          >
            <SectionTitle title="rarity" />
            <div className="rarity_detail">
              <p>
                Each NFT is algorithmically generated by combining 130+ unique
                traits with varying rarity across categories
              </p>
            </div>
          </div>
          <div className="chart_card col-lg-12 d-flex flex-wrap">
            <div
              className="col-lg-6 col-12"
              data-aos="fade-right"
              data-aos-duration="700"
              data-aos-delay="1000"
            >
              <h2>TYPES</h2>
              {rarity_types.map((item, indx) => (
                <div className="single_type_card" key={indx}>
                  <p>{item}</p>
                </div>
              ))}
              <div className="d-flex justify-content-center align-items-center my-5">
                <img
                  src={alert}
                  alt="alert"
                  className="alertImg img-fluid mt-lg-5"
                />
              </div>
            </div>
            <div
              className="col-lg-6 col-12"
              data-aos="fade-left"
              data-aos-duration="700"
              data-aos-delay="1000"
            >
              <h2>TRAITS</h2>
              {rarity_traits.map((item, idx) => (
                <div className="single_trait_card" key={idx}>
                  <div className="d-flex align-items-center">
                    <p>{item.num}</p>
                    <p>{item.text}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Rarity;
